/* CeeLo: a Monte Carlo photon-transport library for computing gamma-ray
 and X-ray detector efficiency - developed as part of InterSpec.

 Copyright 2026 National Technology & Engineering Solutions of Sandia, LLC.
 This library is distributed under the GNU Lesser General Public License,
 version 2.1 or (at your option) any later version.
 */

// Generated by tools/prepare_cross_sections/generate_estar_stopping.py.
// Source: NIST ESTAR / SRD 124; see sources.lock.json. DO NOT EDIT.
#pragma once

#include <cstddef>
#include <cstdint>

namespace ceelo::estar_data {

inline constexpr std::size_t kElementCount = 92;
inline constexpr std::size_t kEnergyCount = 53;
extern const float kLogEnergyKeV[kEnergyCount];
extern const uint16_t kLogCollisionQuantized[kElementCount][kEnergyCount];
extern const uint16_t kLogRadiativeQuantized[kElementCount][kEnergyCount];
extern const float kLogCollisionOffset[kElementCount];
extern const float kLogCollisionScale[kElementCount];
extern const float kLogRadiativeOffset[kElementCount];
extern const float kLogRadiativeScale[kElementCount];

double collision_stopping(int Z, double energy_keV);
double radiative_stopping(int Z, double energy_keV);

} // namespace ceelo::estar_data
