#!/usr/bin/env python3
"""Generate EPQ bremsstrahlung plus BSD xraylib Compton-profile support data.

Photon cross sections/angular factors and atomic relaxation live in their direct
EPICS translation units. This file deliberately contains none of the retired
G4-derived photon or fluorescence arrays.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import math
from pathlib import Path

import xraylib as xrl

from fetch_sources import epq_table_set_sha256, load_lock, sha256_file
from generation_utils import ELEMENT_SYMBOLS, SECTION_END, format_float32, format_rows, write_section
from sb_tables_epq import build_tables, epq_provenance, table_payload_sha256


HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
DEFAULT_LOCK = HERE / "sources.lock.json"
DEFAULT_OUTPUT = ROOT / "src" / "cross_sections" / "element_data.cpp"
DEFAULT_REPORT = HERE / "reports" / "element_support.json"
MAX_SHELL_CONST = 31


def compton_shells(z: int) -> list[tuple[float, float, float]]:
    shells: list[tuple[float, float, float]] = []
    for shell in range(MAX_SHELL_CONST):
        try:
            occupancy = float(xrl.ElectronConfig(z, shell))
        except ValueError:
            occupancy = 0.0
        if occupancy <= 0.0:
            continue
        try:
            binding = float(xrl.EdgeEnergy(z, shell))
            if not math.isfinite(binding) or binding < 0.0:
                binding = 0.0
        except ValueError:
            binding = 0.0
        try:
            j0 = float(xrl.ComptonProfile_Partial(z, shell, 0.0))
            if not math.isfinite(j0) or j0 <= 0.0:
                raise ValueError("invalid profile")
        except ValueError:
            # xraylib lacks separately resolved profiles for a few outer shells.
            # Merge only their occupancy into the preceding represented shell.
            if shells:
                old_occupancy, old_binding, old_j0 = shells[-1]
                shells[-1] = (old_occupancy + occupancy, old_binding, old_j0)
            continue
        shells.append((occupancy, binding, j0))
    if not shells or abs(sum(item[0] for item in shells) - z) > 0.01:
        raise ValueError(f"Z={z}: represented Compton occupancy does not sum to Z")
    return shells


def verify_profile_convention() -> None:
    hydrogen = float(xrl.ComptonProfile_Partial(1, xrl.K_SHELL, 0.0))
    if abs(hydrogen - 0.849) > 0.02:
        raise ValueError(f"unexpected xraylib per-electron H profile J(0)={hydrogen}")


def emit_float_array(out: io.StringIO, name: str, values: list[float]) -> None:
    out.write(f"static const float {name}[{len(values)}] = {{\n")
    out.write(format_rows(values, 8, "    ", format_float32))
    out.write("\n};\n")


def generate_cpp(
    output: Path,
    tables: dict[int, list[list[float]]],
    epq_source: dict,
    shells: dict[int, list[tuple[float, float, float]]],
) -> None:
    out = io.StringIO()
    out.write("""/* CeeLo: a Monte Carlo photon-transport library for computing gamma-ray
 and X-ray detector efficiency - developed as part of InterSpec.

 Copyright 2026 National Technology & Engineering Solutions of Sandia, LLC.
 This library is distributed under the GNU Lesser General Public License,
 version 2.1 or (at your option) any later version.
 */

/// AUTO-GENERATED by tools/prepare_cross_sections/generate_element_support.py.
/// Bremsstrahlung: public-domain NIST EPQ, transformed uniformly as recorded in
/// sources.lock.json. Compton profiles/atomic weights: BSD-licensed xraylib.
/// Photon cross sections/angular factors and relaxation are direct EPICS2023
/// translation units. No Geant4/G4EMLOW coefficient payload appears here.

#include "cross_sections/CrossSectionData.h"

namespace ceelo {

""")
    write_section(out, tables, "uint16", epq_provenance(epq_source))
    out.write(SECTION_END)
    out.write("// Remaining fields contain only permissively sourced element support.\n\n")
    out.write("// xraylib 4.2.1 per-electron Compton profile support.\n")
    for z in range(1, 93):
        values = shells[z]
        emit_float_array(out, f"Z{z}_cs_shell_occ", [item[0] for item in values])
        emit_float_array(out, f"Z{z}_cs_shell_ub", [item[1] for item in values])
        emit_float_array(out, f"Z{z}_cs_shell_j0", [item[2] for item in values])

    out.write("\nextern const ElementData g_element_data[92] = {\n")
    for z in range(1, 93):
        count = len(shells[z])
        out.write(
            f"    {{{z}, Z{z}_sb_chi, {count}, Z{z}_cs_shell_occ, Z{z}_cs_shell_ub, "
            f"Z{z}_cs_shell_j0}}{',' if z < 92 else ''} // {ELEMENT_SYMBOLS[z - 1]}\n"
        )
    out.write("};\n\n")
    weights = [float(xrl.AtomicWeight(z)) for z in range(1, 93)]
    out.write("// Standard atomic weights from xraylib 4.2.1.\n")
    out.write("extern const double g_atomic_weights[92] = {\n")
    out.write(format_rows(weights, 8, "    ", lambda value: f"{value:.9g}"))
    out.write("\n};\n\n} // namespace ceelo\n")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(out.getvalue(), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--epq-tables", type=Path, required=True)
    parser.add_argument("--xraylib-archive", type=Path, required=True)
    parser.add_argument("--lock", type=Path, default=DEFAULT_LOCK)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    args = parser.parse_args()

    lock = load_lock(args.lock)
    epq_source = lock["sources"]["nist_epq"]
    xraylib_source = lock["sources"]["xraylib"]
    if epq_table_set_sha256(args.epq_tables, epq_source["table_glob"]) != epq_source["table_set_sha256"]:
        raise ValueError("EPQ logical table digest mismatch")
    if sha256_file(args.xraylib_archive) != xraylib_source["sha256"]:
        raise ValueError("xraylib source archive digest mismatch")
    if xrl.__version__ != xraylib_source["version"]:
        raise ValueError(f"xraylib module version is {xrl.__version__}, expected {xraylib_source['version']}")

    verify_profile_convention()
    tables, _, _ = build_tables(args.epq_tables)
    shells = {z: compton_shells(z) for z in range(1, 93)}
    generate_cpp(args.output, tables, epq_source, shells)
    args.report.parent.mkdir(parents=True, exist_ok=True)
    report = {
        "schema_version": 1,
        "source_lock_sha256": hashlib.sha256(args.lock.read_bytes()).hexdigest(),
        "epq_payload_sha256_float32_little_endian": table_payload_sha256(tables),
        "xraylib_version": xrl.__version__,
        "xraylib_source_sha256": xraylib_source["sha256"],
        "compton_profile_coefficients": sum(3 * len(value) for value in shells.values()),
        "compton_profile_bytes": sum(12 * len(value) for value in shells.values()),
        "compton_shells_min": min(len(value) for value in shells.values()),
        "compton_shells_max": max(len(value) for value in shells.values()),
        "bremsstrahlung_coefficients": 92 * 27 * 32,
        "bremsstrahlung_encoding": "uint16 with one float32 scale per element",
        "bremsstrahlung_bytes": 92 * 27 * 32 * 2 + 92 * 4,
        "prohibited_g4_payloads": 0,
    }
    args.report.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"Generated {args.output} from locked EPQ and xraylib")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
