#!/usr/bin/env python3
"""Generate all-element stopping tables from locked official NIST ESTAR output.

The upstream STAR source archive remains the algorithm/database provenance.  This
generator consumes the official text-interface results so preparing the tables
does not depend on a host Fortran compiler.  Normal CeeLo builds are offline.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import re
import struct
from pathlib import Path

from fetch_sources import load_lock
from generation_utils import as_float32, format_float32

CEELO_LICENCE_HEADER = """\
/* CeeLo: a Monte Carlo photon-transport library for computing gamma-ray
 and X-ray detector efficiency - developed as part of InterSpec.

 Copyright 2026 National Technology & Engineering Solutions of Sandia, LLC.
 This library is distributed under the GNU Lesser General Public License,
 version 2.1 or (at your option) any later version.
 */
"""



HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
DEFAULT_LOCK = HERE / "sources.lock.json"
DEFAULT_HEADER = ROOT / "src" / "physics" / "estar_stopping_data.h"
DEFAULT_SOURCE = ROOT / "src" / "physics" / "estar_stopping_data.cpp"
DEFAULT_REPORT_DIR = HERE / "reports"
EXPECTED_ENERGIES_MEV = (
    0.010, 0.0125, 0.015, 0.0175, 0.020, 0.025, 0.030, 0.035,
    0.040, 0.045, 0.050, 0.055, 0.060, 0.070, 0.080, 0.090,
    0.100, 0.125, 0.150, 0.175, 0.200, 0.250, 0.300, 0.350,
    0.400, 0.450, 0.500, 0.550, 0.600, 0.700, 0.800, 0.900,
    1.000, 1.250, 1.500, 1.750, 2.000, 2.500, 3.000, 3.500,
    4.000, 4.500, 5.000, 5.500, 6.000, 7.000, 8.000, 9.000,
    10.00, 12.50, 15.00, 17.50, 20.00,
)
ROW_RE = re.compile(
    r"\s+([0-9.]+E[+-][0-9]+)\s+" + r"\s+".join(
        [r"([0-9.]+E[+-][0-9]+)"] * 6
    ) + r"\s*<br>",
)


def parse_table(path: Path) -> list[tuple[float, float, float]]:
    text = path.read_text(encoding="ascii", errors="strict")
    rows = [
        (float(match.group(1)), float(match.group(2)), float(match.group(3)))
        for match in ROW_RE.finditer(text)
    ]
    selected = [row for row in rows if 0.01 <= row[0] <= 20.0]
    energies = tuple(row[0] for row in selected)
    if energies != EXPECTED_ENERGIES_MEV:
        raise ValueError(
            f"{path}: expected {len(EXPECTED_ENERGIES_MEV)} ESTAR nodes, "
            f"found {len(selected)} ({energies[:2]} ... {energies[-2:]})"
        )
    if any(collision <= 0.0 or radiative <= 0.0 for _, collision, radiative in selected):
        raise ValueError(f"{path}: stopping powers must be positive")
    return selected


def logical_digest(tables: dict[int, list[tuple[float, float, float]]]) -> str:
    digest = hashlib.sha256()
    for z in range(1, 93):
        digest.update(struct.pack("<H", z))
        for row in tables[z]:
            digest.update(struct.pack("<ddd", *row))
    return digest.hexdigest()


def format_array(values: list[float], indent: str = "    ", width: int = 8) -> str:
    lines = []
    for begin in range(0, len(values), width):
        lines.append(indent + ", ".join(format_float32(value) for value in values[begin:begin + width]))
    return ",\n".join(lines)


def format_uint16_array(values: list[int], indent: str = "    ", width: int = 12) -> str:
    lines = []
    for begin in range(0, len(values), width):
        lines.append(indent + ", ".join(str(value) for value in values[begin:begin + width]))
    return ",\n".join(lines)


def encode_log_rows(
    tables: dict[int, list[tuple[float, float, float]]], column: int
) -> tuple[list[list[int]], list[float], list[float]]:
    packed: list[list[int]] = []
    offsets: list[float] = []
    scales: list[float] = []
    for z in range(1, 93):
        source = [math.log10(row[column]) for row in tables[z]]
        offset = as_float32(min(source))
        scale = as_float32((max(source) - offset) / 65535.0)
        codes = [
            max(0, min(65535, int(round((value - offset) / scale))))
            for value in source
        ]
        packed.append(codes)
        offsets.append(offset)
        scales.append(scale)
    return packed, offsets, scales


def write_header(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        CEELO_LICENCE_HEADER +
        "// Generated by tools/prepare_cross_sections/generate_estar_stopping.py.\n"
        "// Source: NIST ESTAR / SRD 124; see sources.lock.json. DO NOT EDIT.\n"
        "#pragma once\n\n"
        "#include <cstddef>\n#include <cstdint>\n\n"
        "namespace ceelo::estar_data {\n\n"
        "inline constexpr std::size_t kElementCount = 92;\n"
        "inline constexpr std::size_t kEnergyCount = 53;\n"
        "extern const float kLogEnergyKeV[kEnergyCount];\n"
        "extern const uint16_t kLogCollisionQuantized[kElementCount][kEnergyCount];\n"
        "extern const uint16_t kLogRadiativeQuantized[kElementCount][kEnergyCount];\n"
        "extern const float kLogCollisionOffset[kElementCount];\n"
        "extern const float kLogCollisionScale[kElementCount];\n"
        "extern const float kLogRadiativeOffset[kElementCount];\n"
        "extern const float kLogRadiativeScale[kElementCount];\n\n"
        "double collision_stopping(int Z, double energy_keV);\n"
        "double radiative_stopping(int Z, double energy_keV);\n\n"
        "} // namespace ceelo::estar_data\n",
        encoding="utf-8",
    )


def write_source(path: Path, tables: dict[int, list[tuple[float, float, float]]]) -> None:
    log_energy = [as_float32(math.log10(energy * 1000.0)) for energy in EXPECTED_ENERGIES_MEV]
    collision, collision_offset, collision_scale = encode_log_rows(tables, 1)
    radiative, radiative_offset, radiative_scale = encode_log_rows(tables, 2)
    chunks = [
        "// Generated by tools/prepare_cross_sections/generate_estar_stopping.py.\n",
        "// Source: NIST ESTAR / SRD 124; see sources.lock.json. DO NOT EDIT.\n",
        '#include "physics/estar_stopping_data.h"\n\n',
        "#include <algorithm>\n#include <cmath>\n\n",
        "namespace ceelo::estar_data {\n\n",
        "const float kLogEnergyKeV[kEnergyCount] = {\n",
        format_array(log_energy), "\n};\n\n",
        "const uint16_t kLogCollisionQuantized[kElementCount][kEnergyCount] = {\n",
    ]
    for z, row in enumerate(collision, 1):
        chunks.extend([f"    // Z={z}\n    {{\n", format_uint16_array(row, "        "), "\n    },\n"])
    chunks.extend([
        "};\n\nconst float kLogCollisionOffset[kElementCount] = {\n",
        format_array(collision_offset),
        "\n};\n\nconst float kLogCollisionScale[kElementCount] = {\n",
        format_array(collision_scale),
        "\n};\n\nconst uint16_t kLogRadiativeQuantized[kElementCount][kEnergyCount] = {\n",
    ])
    for z, row in enumerate(radiative, 1):
        chunks.extend([f"    // Z={z}\n    {{\n", format_uint16_array(row, "        "), "\n    },\n"])
    chunks.extend([
        "};\n\nconst float kLogRadiativeOffset[kElementCount] = {\n",
        format_array(radiative_offset),
        "\n};\n\nconst float kLogRadiativeScale[kElementCount] = {\n",
        format_array(radiative_scale),
        "\n};\n\n",
        "namespace {\n",
        "double interpolate(const uint16_t table[kElementCount][kEnergyCount],\n",
        "                   const float offset[kElementCount],\n",
        "                   const float scale[kElementCount],\n",
        "                   int Z, double energy_keV)\n",
        "{\n",
        "    if (Z < 1 || Z > static_cast<int>(kElementCount) || energy_keV <= 0.0) return 0.0;\n",
        "    const double x = std::log10(std::clamp(energy_keV, 10.0, 20000.0));\n",
        "    const float* begin = kLogEnergyKeV;\n",
        "    const float* end = begin + kEnergyCount;\n",
        "    const float* upper = std::upper_bound(begin, end, static_cast<float>(x));\n",
        "    const std::size_t zi = static_cast<std::size_t>(Z - 1);\n",
        "    const auto decode = [&](std::size_t i) {\n",
        "        return static_cast<double>(offset[zi]) + static_cast<double>(table[zi][i]) * scale[zi];\n",
        "    };\n",
        "    if (upper == begin) return std::pow(10.0, decode(0));\n",
        "    if (upper == end) return std::pow(10.0, decode(kEnergyCount - 1));\n",
        "    const std::size_t hi = static_cast<std::size_t>(upper - begin);\n",
        "    const std::size_t lo = hi - 1;\n",
        "    const double t = (x - begin[lo]) / (begin[hi] - begin[lo]);\n",
        "    const double y_lo = decode(lo);\n",
        "    const double y = y_lo + t * (decode(hi) - y_lo);\n",
        "    return std::pow(10.0, y);\n",
        "}\n",
        "} // namespace\n\n",
        "double collision_stopping(int Z, double energy_keV)\n",
        "{\n    return interpolate(kLogCollisionQuantized, kLogCollisionOffset, kLogCollisionScale, Z, energy_keV);\n}\n\n",
        "double radiative_stopping(int Z, double energy_keV)\n",
        "{\n    return interpolate(kLogRadiativeQuantized, kLogRadiativeOffset, kLogRadiativeScale, Z, energy_keV);\n}\n\n",
        "} // namespace ceelo::estar_data\n",
    ])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(CEELO_LICENCE_HEADER + "".join(chunks), encoding="utf-8")


def representation_error(
    tables: dict[int, list[tuple[float, float, float]]], column: int
) -> tuple[float, float]:
    errors = []
    packed, offsets, scales = encode_log_rows(tables, column + 1)
    for z in range(1, 93):
        for index, (energy, collision, radiative) in enumerate(tables[z]):
            source = (collision, radiative)[column]
            stored_x = as_float32(math.log10(energy * 1000.0))
            stored_y = offsets[z - 1] + packed[z - 1][index] * scales[z - 1]
            represented = 10.0 ** stored_y
            # At native nodes runtime's float x comparison reaches this same value.
            errors.append(abs(represented / source - 1.0))
            if not math.isfinite(stored_x):
                raise ValueError("non-finite encoded energy")
    errors.sort()
    return errors[int(0.95 * (len(errors) - 1))], errors[-1]


def write_reports(
    report_dir: Path,
    lock_hash: str,
    table_hash: str,
    collision_error: tuple[float, float],
    radiative_error: tuple[float, float],
) -> None:
    report_dir.mkdir(parents=True, exist_ok=True)
    shared_grid_bytes = len(EXPECTED_ENERGIES_MEV) * 4
    coefficients = 92 * len(EXPECTED_ENERGIES_MEV)
    report = {
        "schema_version": 1,
        "generator": "generate_estar_stopping.py",
        "source_lock_sha256": lock_hash,
        "logical_table_sha256": table_hash,
        "elements": 92,
        "energy_nodes": len(EXPECTED_ENERGIES_MEV),
        "energy_range_keV": [10.0, 20000.0],
        "encoding": "per-element affine uint16(log10 value)",
        "shared_grid": {"coefficients": 53, "bytes": shared_grid_bytes},
        "processes": {
            "collision_stopping": {
                "native_coefficients": coefficients,
                "retained_coefficients": coefficients,
                "coefficient_bytes": coefficients * 2,
                "metadata_bytes": 92 * 2 * 4,
                "p95_native_representation_error_percent": collision_error[0] * 100.0,
                "maximum_native_representation_error_percent": collision_error[1] * 100.0,
            },
            "radiative_stopping": {
                "native_coefficients": coefficients,
                "retained_coefficients": coefficients,
                "coefficient_bytes": coefficients * 2,
                "metadata_bytes": 92 * 2 * 4,
                "p95_native_representation_error_percent": radiative_error[0] * 100.0,
                "maximum_native_representation_error_percent": radiative_error[1] * 100.0,
            },
        },
        "notes": [
            "All 53 NIST standard-grid nodes from 10 keV through 20 MeV are retained for every Z=1..92.",
            "The shared energy grid is counted separately and not charged to either stopping process.",
            "NIST's text output is rounded to four significant figures; this report measures only the additional affine uint16 log-domain encoding error.",
        ],
    }
    (report_dir / "stopping_estar.json").write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    with (report_dir / "stopping_estar.csv").open("w", newline="", encoding="utf-8") as stream:
        writer = csv.writer(stream, lineterminator="\n")
        writer.writerow([
            "process", "native_coefficients", "retained_coefficients", "encoding",
            "coefficient_bytes", "metadata_bytes", "shared_grid_bytes", "p95_error_percent", "max_error_percent",
        ])
        for name, values in report["processes"].items():
            writer.writerow([
                name, values["native_coefficients"], values["retained_coefficients"],
                report["encoding"], values["coefficient_bytes"], values["metadata_bytes"],
                shared_grid_bytes if name == "collision_stopping" else 0,
                values["p95_native_representation_error_percent"],
                values["maximum_native_representation_error_percent"],
            ])
    process_lines = []
    for name, values in report["processes"].items():
        process_lines.append(
            f"| {name} | {values['native_coefficients']:,} | {values['retained_coefficients']:,} | "
            f"{values['coefficient_bytes']:,} | {values['p95_native_representation_error_percent']:.6g}% | "
            f"{values['maximum_native_representation_error_percent']:.6g}% |"
        )
    (report_dir / "stopping_estar.md").write_text(
        "# NIST ESTAR stopping-table report\n\n"
        "All 53 official nodes from 10 keV through 20 MeV are retained for every element Z=1–92. "
        "The downloadable STAR source/database is locked as provenance; values are taken from the official "
        "NIST ESTAR text interface and stored as per-element affine uint16 logarithms.\n\n"
        "| Process | Native | Retained | Coefficient bytes | p95 encoding error | Max encoding error |\n"
        "|---|---:|---:|---:|---:|---:|\n" + "\n".join(process_lines) + "\n\n"
        f"Shared grid: 53 float32 coefficients ({shared_grid_bytes} bytes), reported once.\n\n"
        f"Logical source digest: `{table_hash}`.\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--estar-dir", type=Path, required=True)
    parser.add_argument("--lock", type=Path, default=DEFAULT_LOCK)
    parser.add_argument("--header", type=Path, default=DEFAULT_HEADER)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--report-dir", type=Path, default=DEFAULT_REPORT_DIR)
    args = parser.parse_args()

    lock = load_lock(args.lock)
    source_lock = lock["sources"]["nist_estar_text"]
    tables = {
        z: parse_table(args.estar_dir / f"estar-text-Z{z:03d}.html")
        for z in range(1, 93)
    }
    digest = logical_digest(tables)
    if digest != source_lock["logical_table_sha256"]:
        raise ValueError(
            "ESTAR logical-table SHA-256 mismatch: "
            f"expected {source_lock['logical_table_sha256']}, got {digest}"
        )
    write_header(args.header)
    write_source(args.source, tables)
    collision_error = representation_error(tables, 0)
    radiative_error = representation_error(tables, 1)
    write_reports(
        args.report_dir,
        hashlib.sha256(args.lock.read_bytes()).hexdigest(),
        digest,
        collision_error,
        radiative_error,
    )
    print(f"Generated {args.source} from 92 x 53 locked ESTAR nodes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
