find_package(Git)
include(FetchContent)

# ------------------------------------------------------------------
# Prefer local copies that CMake has already unpacked to build/_deps
# ------------------------------------------------------------------
macro(use_local_dep dep_name)
  set(_local_dir "${CMAKE_BINARY_DIR}/_deps/${dep_name}-src")
  if(EXISTS "${_local_dir}/CMakeLists.txt")
    message(STATUS "Using cached ${dep_name} from ${_local_dir}")
    set(FETCHCONTENT_SOURCE_DIR_${dep_name} "${_local_dir}" CACHE PATH "" FORCE)
    set(FETCHCONTENT_UPDATES_DISCONNECTED_${dep_name} ON CACHE BOOL "" FORCE)
  endif()
endmacro()

foreach(_dep IN ITEMS boost wt zlib eigen ceres-solver wxWidgets)
  use_local_dep(${_dep})
endforeach()

# We'll set the install directory to somewhere not /usr/local or something, so we dont
#  mess the system filesystem up; Wt and zlib will install
#  If you want to install the packages, it looks like doing the following command
#   should place them in prefix directory - although I think I patched the install
#   functionality out of zlib and Wt... I should restore.
#     cmake --build . --config Release -j8 --target install
set( CMAKE_INSTALL_PREFIX "${CMAKE_BINARY_DIR}/prefix" CACHE INTERNAL "" )

set(BOOST_ENABLE_CMAKE ON CACHE INTERNAL "" )


# Currently installing dependencies to "prefix" of the build directory is a work in progress,
#  so just doing it for iOS build, at the moment.... Boost and Wt seem to be not working - not sure if this is something I did, or not
if( InterSpec_IOS )
  set( INSTALL_DEPENDENCIES_IN_BUILD_DIR ON )
else( InterSpec_IOS )
  set( INSTALL_DEPENDENCIES_IN_BUILD_DIR OFF )
endif( InterSpec_IOS )

message("")
message("")
message("It may take 10 or 20 minutes to clone into boost and Wt repos...")
message("")


set( BOOST_IOSTREAMS_ENABLE_ZSTD OFF CACHE INTERNAL ""  )
set( BOOST_IOSTREAMS_ENABLE_ZLIB OFF CACHE INTERNAL ""  )
set( BOOST_IOSTREAMS_ENABLE_LZMA OFF CACHE INTERNAL ""  )
set( BOOST_IOSTREAMS_ENABLE_BZIP2 OFF CACHE INTERNAL ""  )
set( Boost_NOWIDE_WERROR OFF CACHE INTERNAL ""  )
#set( BOOST_EXCLUDE_LIBRARIES nowide log CACHE INTERNAL ""  )

set( BUILD_SHARED_LIBS OFF CACHE INTERNAL "Build SHARED libraries" )

# TODO: set BOOST libraries to not build, like wave, beast, wserialization, etc

# set( FETCHCONTENT_QUIET FALSE )

# ---- Boost 1.84.0 ----
set(LOCAL_BOOST_DIR "${CMAKE_BINARY_DIR}/_deps/boost-src")
if(EXISTS "${LOCAL_BOOST_DIR}/CMakeLists.txt")
  message(STATUS "Using local Boost from ${LOCAL_BOOST_DIR}")
  set(BOOST_FETCHCONTENT_SOURCE SOURCE_DIR "${LOCAL_BOOST_DIR}")
  FetchContent_Declare( boost ${BOOST_FETCHCONTENT_SOURCE} )
else()
  set(BOOST_FETCHCONTENT_SOURCE
    GIT_REPOSITORY https://github.com/boostorg/boost.git
    GIT_TAG        ad09f667e61e18f5c31590941e748ac38e5a81bf # boost-1.84.0
    GIT_SHALLOW    ON
  )
  FetchContent_Declare( boost ${BOOST_FETCHCONTENT_SOURCE} )
endif()

FetchContent_MakeAvailable( boost )
FetchContent_GetProperties( boost )


# Wt 4 calls find_package(Boost COMPONENTS ...). The boostorg/boost super-repo
# added via add_subdirectory provides Boost::* INTERFACE/STATIC targets but does
# not write a BoostConfig.cmake on disk, so find_package(Boost) cannot locate
# it through either CONFIG mode (no config file) or MODULE mode (FindBoost.cmake
# doesn't understand the super-repo's libs/<lib>/include layout). Write a shim
# BoostConfig.cmake that just declares the in-tree Boost::* targets as found,
# then force Wt's find_package(Boost) into CONFIG mode via CMP0167 NEW so it
# uses our shim instead of legacy FindBoost.cmake.
set( _interspec_boost_shim_dir "${CMAKE_BINARY_DIR}/cmake_shims/Boost" )
file( MAKE_DIRECTORY "${_interspec_boost_shim_dir}" )

# Wt uses Boost_INCLUDE_DIRS via INCLUDE_DIRECTORIES(${BOOST_INCLUDE_DIRS}) to
# resolve headers like <boost/asio/version.hpp>. In an installed Boost prefix
# all headers live under one directory; in the super-repo they're scattered
# across libs/<lib>/include and libs/numeric/<lib>/include. Glob both layouts.
file( GLOB _interspec_boost_lib_incs LIST_DIRECTORIES TRUE
  "${boost_SOURCE_DIR}/libs/*/include"
  "${boost_SOURCE_DIR}/libs/numeric/*/include"
)
set( _interspec_boost_includes "" )
foreach( _dir IN LISTS _interspec_boost_lib_incs )
  if( IS_DIRECTORY "${_dir}/boost" )
    list( APPEND _interspec_boost_includes "${_dir}" )
  endif()
endforeach()
unset( _interspec_boost_lib_incs )

# Render the include list as a CMake list literal for the shim file.
string( REPLACE ";" "\;" _interspec_boost_includes_lit "${_interspec_boost_includes}" )

file( WRITE "${_interspec_boost_shim_dir}/BoostConfig.cmake" "\
# Auto-generated by InterSpec FetchInterSpecDeps.cmake.
# Declares the in-tree boostorg/boost targets as a found Boost installation,
# so that consumers calling find_package(Boost COMPONENTS …) succeed without
# requiring an installed Boost prefix.
set(Boost_VERSION_STRING \"1.84.0\")
set(Boost_VERSION \"1.84.0\")
set(Boost_VERSION_MAJOR 1)
set(Boost_VERSION_MINOR 84)
set(Boost_VERSION_PATCH 0)
set(Boost_VERSION_COUNT 3)
set(Boost_INCLUDE_DIRS \"${_interspec_boost_includes_lit}\")
if(Boost_INCLUDE_DIRS)
  list(GET Boost_INCLUDE_DIRS 0 Boost_INCLUDE_DIR)
else()
  set(Boost_INCLUDE_DIR \"\")
endif()
set(Boost_LIBRARY_DIRS \"\")
set(Boost_LIBRARIES \"\")
foreach(_comp \${Boost_FIND_COMPONENTS})
  if(TARGET Boost::\${_comp})
    set(Boost_\${_comp}_FOUND TRUE)
    string(TOUPPER \"\${_comp}\" _comp_uc)
    set(Boost_\${_comp_uc}_LIBRARY Boost::\${_comp})
    list(APPEND Boost_LIBRARIES Boost::\${_comp})
  else()
    set(Boost_\${_comp}_FOUND FALSE)
    if(Boost_FIND_REQUIRED_\${_comp} OR Boost_FIND_REQUIRED)
      message(FATAL_ERROR \"Required Boost component '\${_comp}' is not provided by the in-tree boostorg/boost.\")
    endif()
  endif()
endforeach()
unset(_comp_uc)
set(Boost_FOUND TRUE)
" )

unset( _interspec_boost_includes_lit )

# Exposed for the top-level CMakeLists.txt FetchContent branch to add to
# InterSpecLib's include directories — boost::numeric::ublas (which InterSpec
# uses) transitively requires boost::serialization headers etc., so the whole
# set is needed.
set( INTERSPEC_FETCH_BOOST_INCLUDES "${_interspec_boost_includes}" )
unset( _interspec_boost_includes )
file( WRITE "${_interspec_boost_shim_dir}/BoostConfigVersion.cmake" "\
set(PACKAGE_VERSION \"1.84.0\")
if(PACKAGE_FIND_VERSION AND (PACKAGE_FIND_VERSION VERSION_GREATER \"1.84.0\"))
  set(PACKAGE_VERSION_UNSUITABLE TRUE)
else()
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
  if(PACKAGE_FIND_VERSION AND (PACKAGE_FIND_VERSION VERSION_EQUAL \"1.84.0\"))
    set(PACKAGE_VERSION_EXACT TRUE)
  endif()
endif()
" )
set( Boost_DIR "${_interspec_boost_shim_dir}" CACHE PATH "Path to Boost shim config for FetchContent build" FORCE )
# Wt's cmake_minimum_required(3.13) leaves CMP0167 at OLD by default — override
# so Wt's find_package(Boost) prefers CONFIG mode and consumes our shim.
set( CMAKE_POLICY_DEFAULT_CMP0167 NEW )
# Likewise quiet the BOOST_ROOT case-sensitivity warning from CMP0144.
set( CMAKE_POLICY_DEFAULT_CMP0144 NEW )


# ---- Wt 4.12.6 ----
set( SHARED_LIBS OFF CACHE INTERNAL "" )
set( ENABLE_HARU OFF CACHE INTERNAL "" )
set( ENABLE_SSL OFF CACHE INTERNAL "" )
set( CONNECTOR_FCGI OFF CACHE INTERNAL "" )
set( BUILD_EXAMPLES OFF CACHE INTERNAL "" )
set( BUILD_TESTS OFF CACHE INTERNAL "" )
set( ENABLE_MYSQL OFF CACHE INTERNAL "" )
set( ENABLE_POSTGRES OFF CACHE INTERNAL "" )
set( ENABLE_PANGO OFF CACHE INTERNAL "" )
set( ENABLE_FIREBIRD OFF CACHE INTERNAL "" )
set( ENABLE_MSSQLSERVER OFF CACHE INTERNAL "" )
set( ENABLE_OPENGL ON CACHE INTERNAL "" )
set( ENABLE_QT4 OFF CACHE INTERNAL "" )
set( ENABLE_QT5 OFF CACHE INTERNAL "" )
set( ENABLE_QT6 OFF CACHE INTERNAL "" )
set( ENABLE_LIBWTTEST OFF CACHE INTERNAL "" )
set( ENABLE_SAML OFF CACHE INTERNAL "" )
set( ENABLE_UNWIND OFF CACHE INTERNAL "" )
set( HTTP_WITH_ZLIB OFF CACHE INTERNAL "" )

# Apple's libc++ on iOS (and older macOS) does not ship `std::chrono::time_zone`,
# so force Wt to use the bundled Howard Hinnant `date` library instead of the
# standard-library implementation. This matches what the manual dep_build_*.sh
# scripts pass, and is required for the iOS build.
set( WT_CPP20_DATE_TZ_IMPLEMENTATION "date" CACHE STRING "" FORCE )

set(LOCAL_WT_DIR "${CMAKE_BINARY_DIR}/_deps/wt-src")
if(EXISTS "${LOCAL_WT_DIR}/CMakeLists.txt")
  message(STATUS "Using local Wt from ${LOCAL_WT_DIR}")
  set(WT_FETCHCONTENT_SOURCE SOURCE_DIR "${LOCAL_WT_DIR}")
else()
  set(WT_FETCHCONTENT_SOURCE
    GIT_REPOSITORY https://github.com/emweb/wt.git
    GIT_TAG        4d158458b06554192c63389e098ad03e5e35a713 # 4.12.6
    GIT_SHALLOW    ON
  )
endif()

FetchContent_Declare(
  wt
  ${WT_FETCHCONTENT_SOURCE}
)


# Suppress install rules from Wt (and other subdeps) to avoid export set
# errors from references to boost/abseil targets not in the same export set.
# Both branches need this: the boost super-repo's per-lib targets (boost_thread,
# boost_filesystem, boost_headers, ...) are not in Wt's install export set, so
# Wt's `install(EXPORT ...)` fails at CMake Generate time without it.
set( _prev_skip_install_rules ${CMAKE_SKIP_INSTALL_RULES} )
set( CMAKE_SKIP_INSTALL_RULES ON )

if( INSTALL_DEPENDENCIES_IN_BUILD_DIR )
  # We will explicitly populate Wt and boost, rather than using this next line, so this way when the user
  #  builds the install target (e.g., for electron build), it wont install stuff to /usr/local
  FetchContent_MakeAvailable( wt boost )
else( INSTALL_DEPENDENCIES_IN_BUILD_DIR )
  FetchContent_GetProperties(wt)
  if(NOT wt_POPULATED)
    FetchContent_Populate(wt)
    add_subdirectory(${wt_SOURCE_DIR} ${wt_BINARY_DIR} EXCLUDE_FROM_ALL)
  endif()

  # Since we arent installing Wt, the InterSpec CMakeLists.txt wont find Wt resources,
  #  so we'll hard code this directory.
  set(WT_RESOURCES_DIRECTORY "${wt_SOURCE_DIR}/resources" CACHE INTERNAL "Set Wt resources dir")

  # If we run the Cmake "install" target (e.g., for Electron build), we'll get an error because
  # ${boost_BINARY_DIR}/cmake_install.cmake doesnt exist, so we'll just put a dummy
  # there, and things seem to work
  #   However, the proper fix would be something like:
  #     https://stackoverflow.com/questions/65527126/disable-install-for-fetchcontent#answer-65529161
  #   Or maybe even better yet, we should modify the patching for Wt and zlib to remove the instal(...) commands
  write_file( "${boost_BINARY_DIR}/cmake_install.cmake" "# This is a dummy patch file the InterSpec build put in" )
endif( INSTALL_DEPENDENCIES_IN_BUILD_DIR )



# macOS, iOS, and Android all have zlib already - we dont need to build it
if( NOT APPLE AND NOT ANDROID )
  set( BUILD_SHARED_LIBS OFF CACHE INTERNAL "Build SHARED libraries" )
  set( ZLIB_BUILD_EXAMPLES OFF CACHE INTERNAL "Skip zlib examples/tests" )

  FetchContent_Declare(
    zlib
    GIT_REPOSITORY https://github.com/madler/zlib.git
    GIT_TAG        v1.3.1
    GIT_SHALLOW    ON
  )

  FetchContent_GetProperties(zlib)
  if( NOT zlib_POPULATED )
    FetchContent_Populate(zlib)
    add_subdirectory( ${zlib_SOURCE_DIR} ${zlib_BINARY_DIR} EXCLUDE_FROM_ALL )
  endif()

  FetchContent_MakeAvailable( zlib )

  # Upstream zlib (1.3.x) names its static library target `zlibstatic` (the shared one is `zlib`).
  # We want consumers using the standard `ZLIB::ZLIB` interface to get the static build.
  if( NOT TARGET ZLIB::ZLIB )
    add_library( ZLIB::ZLIB ALIAS zlibstatic )
    set( ZLIB_LIBRARY zlibstatic CACHE INTERNAL "set zlib static lib" )
    set( ZLIB_INCLUDE_DIR "${zlib_SOURCE_DIR};${zlib_BINARY_DIR}" CACHE INTERNAL "set zlib include dirs" )
  endif()
endif( NOT APPLE AND NOT ANDROID )



# ---- Eigen 5.0.1 ----
set( EIGEN_BUILD_SHARED_LIBS OFF CACHE INTERNAL "" )
set( EIGEN_BUILD_DOC OFF CACHE INTERNAL "" )
set( EIGEN_BUILD_TESTING OFF CACHE INTERNAL "" )
set( EIGEN_BUILD_PKGCONFIG OFF )
set( EIGEN_BUILD_CMAKE_PACKAGE ON CACHE INTERNAL "" )
set( EIGEN_MPL2_ONLY ON CACHE INTERNAL "" )

set(LOCAL_EIGEN_DIR "${CMAKE_BINARY_DIR}/_deps/eigen-src")
if(EXISTS "${LOCAL_EIGEN_DIR}/CMakeLists.txt")
  message(STATUS "Using local Eigen from ${LOCAL_EIGEN_DIR}")
  set(EIGEN_FETCHCONTENT_SOURCE SOURCE_DIR "${LOCAL_EIGEN_DIR}")
else()
  set(EIGEN_FETCHCONTENT_SOURCE
    GIT_REPOSITORY https://gitlab.com/libeigen/eigen.git
    GIT_TAG        bc3b39870ecb690a623a3f49149a358b95c5781d  # version 5.0.1
    UPDATE_DISCONNECTED TRUE
  )
endif(EXISTS "${LOCAL_EIGEN_DIR}/CMakeLists.txt")

FetchContent_Declare( eigen ${EIGEN_FETCHCONTENT_SOURCE} )
FetchContent_MakeAvailable( eigen )

# For Android and iOS, we need to force the path information for Eigen, for some reason.
# Eigen's FetchContent build writes Eigen3Config.cmake directly into ${eigen_BINARY_DIR}
# (not into share/eigen3/cmake/), so point Eigen3_DIR there.  CMAKE_PREFIX_PATH is also
# set so any downstream find_package(Eigen3 ...) succeeds even if it ignores Eigen3_DIR.
set( CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${eigen_BINARY_DIR}" CACHE STRING "Modules for CMake" FORCE )
set( Eigen3_DIR "${eigen_BINARY_DIR}" CACHE PATH "Path to Eigen3Config.cmake" FORCE )
list( APPEND CMAKE_PREFIX_PATH "${eigen_BINARY_DIR}" )


# ---- Ceres-Solver (HEAD from Mar 22, 2026) ----
# Ceres bundles its own abseil in third_party/abseil-cpp and will use it
# automatically.  We set abseil options before Ceres so they propagate.
set( ABSL_BUILD_TESTING OFF CACHE INTERNAL "" )
set( ABSL_USE_GOOGLETEST_HEAD OFF CACHE INTERNAL "" )
set( ABSL_PROPAGATE_CXX_STD ON CACHE INTERNAL "" )
set( GFLAGS OFF CACHE INTERNAL "" )
set( ACCELERATESPARSE OFF CACHE INTERNAL "" )
set( USE_CUDA OFF CACHE INTERNAL "" )
set( EXPORT_BUILD_DIR OFF CACHE INTERNAL "" )
set( BUILD_TESTING OFF CACHE INTERNAL "" )
set( BUILD_EXAMPLES OFF CACHE INTERNAL "" )
set( PROVIDE_UNINSTALL_TARGET OFF CACHE INTERNAL "" )

set(LOCAL_CERES_DIR "${CMAKE_BINARY_DIR}/_deps/ceres-solver-src")
if(EXISTS "${LOCAL_CERES_DIR}/CMakeLists.txt")
  message(STATUS "Using local Ceres Solver from ${LOCAL_CERES_DIR}")
  set(CERES_FETCHCONTENT_SOURCE SOURCE_DIR "${LOCAL_CERES_DIR}" EXCLUDE_FROM_ALL)
else()
  # NOTE: GIT_SHALLOW=TRUE only works when GIT_TAG points to a branch/tag tip;
  # this hash is mid-history, so shallow clones omit it and checkout fails.
  set(CERES_FETCHCONTENT_SOURCE
      GIT_REPOSITORY https://github.com/ceres-solver/ceres-solver.git
      GIT_TAG        2f946a582ae4a9e7ee0492030ec12d9b1f3dbade  # HEAD from Mar 22, 2026
      UPDATE_DISCONNECTED TRUE
      EXCLUDE_FROM_ALL
  )
endif()

FetchContent_Declare( ceres-solver ${CERES_FETCHCONTENT_SOURCE} )
FetchContent_MakeAvailable( ceres-solver )


if( BUILD_AS_WX_WIDGETS_APP )
  set(wxBUILD_SHARED OFF CACHE BOOL "")

  if(WIN32)
    set(wxUSE_WEBVIEW_EDGE ON CACHE BOOL "")
    set(wxUSE_WEBVIEW_EDGE_STATIC ON CACHE BOOL "")
    # TODO: static runtime should be set off of wxInterSpec_USE_MSVC_MultiThreadDLL
    set(wxBUILD_USE_STATIC_RUNTIME ON CACHE BOOL "")
  endif(WIN32)

  # Think by default sub-modules are also retrieved - but not tested yet
  FetchContent_Declare( wxWidgets
    GIT_REPOSITORY https://github.com/wxWidgets/wxWidgets.git
    GIT_TAG        97e99707c5d2271a70cb686720b48dbf34ced496 # release-3.2.1
    GIT_SHALLOW    ON
    # GIT_PROGRESS TRUE # Also need FETCHCONTENT_QUIET
  )

  FetchContent_GetProperties(wxWidgets)
  if(NOT wxWidgets_POPULATED)
    FetchContent_Populate(wxWidgets)
    add_subdirectory(${wxWidgets_SOURCE_DIR} ${wxWidgets_BINARY_DIR} EXCLUDE_FROM_ALL)
  endif(NOT wxWidgets_POPULATED)

  # write_file( "${wxWidgets_BINARY_DIR}/cmake_install.cmake" "# This is a dummy patch file the InterSpec build put in" )
endif( BUILD_AS_WX_WIDGETS_APP )

# Restore install rules for the main project
if( DEFINED _prev_skip_install_rules )
  set( CMAKE_SKIP_INSTALL_RULES ${_prev_skip_install_rules} )
else()
  unset( CMAKE_SKIP_INSTALL_RULES )
endif()

message("Building Wt and boost may also take up to a couple hours...")
