# GENERATED by target/tools/wt_resource_audit/wt_resource_audit.py -- do not edit by hand.
# Wt resources/ paths InterSpec does not use; removed from the bundled copy.
# Re-generate after a Wt upgrade:  python3 target/tools/wt_resource_audit/wt_resource_audit.py
set( WT_RESOURCES_PRUNE_LIST
  "collapse-rtl.gif"
  "expand-rtl.gif"
  "font-awesome"
  "jPlayer"
  "line-last-rtl.gif"
  "line-middle-rtl.gif"
  "themes/bootstrap"
  "themes/default/nav-minus-rtl.gif"
  "themes/default/nav-plus-rtl.gif"
  "themes/default/wt_ie.css"
  "themes/default/wt_ie6.css"
  "themes/polished"
  "tv-line-last-rtl.gif"
)
